findyourfits/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, sell_product_entry, show_xml, show_json, show_json_by_id, show_xml_by_id
from main.views import register, login_user, logout_user, edit_product, hapus_product, add_product_ajax
from main.views import create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('sell-product-entry', sell_product_entry, name='sell_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', hapus_product, name='hapus_product'),
    path('add-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-product-flutter/', create_product_flutter, name='create_product_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %} {% endblock meta %}
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
        }
    </style>
  </head>
  <body>
    {% block content %}
    {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="sticky top-0 bg-gradient-to-r from-cyan-950 to-cyan-700 border-gray-200 z-50">
    <div class="max-w-screen-xl mx-auto p-4">
        <div class="flex items-center justify-between">
            <!-- Logo -->
            <div class="flex-shrink-0">
                <a class="flex items-center space-x-3 rtl:space-x-reverse">
                    <span class="self-center text-2xl sm:text-3xl md:text-2xl font-semibold whitespace-nowrap text-cyan-200">FindYourFits</span>
                </a>
            </div>

            <!-- Elemen tengah navbar -->
            <div class="hidden md:flex items-center justify-center flex-grow">
                <div class="flex space-x-4">
                    <a href="{% url 'main:show_main' %}" class="text-cyan-200 hover:bg-cyan-600 hover:text-white rounded-md px-4 py-2 text-base font-medium">Home</a>

                </div>
            </div>

            <div class="flex items-center">
                <!-- Hamburger button -->
                <button type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm 
                text-cyan-200 rounded-lg md:hidden hover:bg-cyan-600 
                focus:outline-none focus:ring-2 focus:ring-cyan-300 mobile-menu-button" aria-controls="navbar-cta" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                    </svg>
                </button>
                <!-- Logout -->
                <a href="{% url 'main:logout' %}" class="hidden md:block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300 ml-4">
                    Logout
                </a>
            </div>
        </div>
    </div>

    <!-- Mobile -->
    <div class="hidden w-full md:hidden" id="navbar-cta">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-cyan-800 rounded-b-lg shadow-lg">
            <a href="{% url 'main:show_main' %}" class="text-cyan-100 hover:bg-cyan-600 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Home</a>
            <a href="{% url 'main:logout' %}" class="text-white bg-red-500 hover:bg-red-600 block px-3 py-2 rounded-md text-base font-medium">Logout</a>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const mobileMenuButton = document.querySelector('.mobile-menu-button');
            const mobileMenu = document.getElementById('navbar-cta');

            mobileMenuButton.addEventListener('click', function() {
                mobileMenu.classList.toggle('hidden');
            });
        });
    </script>
</nav>