findyourfits/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, sell_product_entry, show_xml, show_json, show_json_by_id, show_xml_by_id
from main.views import register, login_user, logout_user, edit_product, hapus_product, add_product_ajax
from main.views import create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('sell-product-entry', sell_product_entry, name='sell_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', hapus_product, name='hapus_product'),
    path('add-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-product-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
import uuid
from django.db import models
# Tugas 4
from django.contrib.auth.models import User

# Create your models here.
class ProductEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    name = models.CharField(max_length=200)
    price = models.IntegerField()
    stock = models.IntegerField() # tambahan
    condition = models.CharField(max_length=30) # used or new
    description = models.TextField() # tambahan

main/forms.py
from django.forms import ModelForm
from main.models import ProductEntry
from django.utils.html import strip_tags



class ProductEntryForm(ModelForm):
    class Meta:
        model = ProductEntry
        fields = ["name", "price", "stock", "condition", "description"]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Styling untuk semua field
        common_styles = 'w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent'
        
        # ubah class dan placeholder untuk setiap field
        self.fields['name'].widget.attrs.update({
            'class': common_styles,
            'placeholder': 'Masukkan nama produk'
        })
        self.fields['price'].widget.attrs.update({
            'class': common_styles,
            'placeholder': 'Masukkan harga produk'
        })
        self.fields['stock'].widget.attrs.update({
            'class': common_styles,
            'placeholder': 'Masukkan stok produk'
        })
        self.fields['condition'].widget.attrs.update({
            'class': common_styles,
            'placeholder': 'Masukkan kondisi produk'
        })  
        self.fields['description'].widget.attrs.update({
            'class': common_styles,
            'placeholder': 'Masukkan deskripsi produk',
            'rows': '4'
        })
        
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_condition(self):
        condition = self.cleaned_data["condition"]
        return strip_tags(condition)
    
    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from main.forms import ProductEntryForm
from main.models import ProductEntry
# === Tugas 4 ===
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
# Authorization
from django.contrib.auth.decorators import login_required
# Cookies
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
# Tugas 6
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'user_name': request.user.username,
        'name': 'Daffa Desra Hastiar',
        'npm': '2306165490',
        'class': 'PBP C',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def sell_product_entry(request):
    form = ProductEntryForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')
    
    context = {'form': form}
    return render(request, "sell_product_entry.html", context)

def show_xml(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun anda berhasil dibuat!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return redirect('main:login')

def edit_product(request, id):
    product = ProductEntry.objects.get(pk = id)

    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def hapus_product(request, id):
    product = ProductEntry.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

# Tugas 6
@csrf_exempt
@require_POST
def add_product_ajax(request): 
    name = strip_tags(request.POST.get("name"))
    price = request.POST.get("price")
    stock = request.POST.get("stock")
    condition = strip_tags(request.POST.get("condition"))
    description = strip_tags(request.POST.get("description"))
    user = request.user

    new_product = ProductEntry(
        name=name, price=price,
        stock=stock, condition=condition,
        description=description, user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = ProductEntry.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            stock=int(data["stock"]),
            condition=data["condition"],
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_product.html
<div class="bg-gradient-to-br from-white to-cyan-100 rounded-lg shadow-lg overflow-hidden flex flex-col h-full transform hover:scale-105 transition duration-300 border border-cyan-100">
  <div class="p-4 flex-grow flex flex-col">
      <h2 class="text-xl sm:text-2xl md:text-xl font-semibold mb-3 text-cyan-800 line-clamp-2">{{ product.name }}</h2>
      <div class="space-y-2">
          <p class="text-base sm:text-lg text-gray-700">
              <span class="font-semibold text-cyan-700">Harga:</span> 
              <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">Rp. {{ product.price }}</span>
          </p>
          <p class="text-base sm:text-lg text-gray-700">
              <span class="font-semibold text-cyan-700">Stok:</span> 
              <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">{{ product.stock }} pcs</span>
          </p>
          <p class="text-base sm:text-lg text-gray-700">
              <span class="font-semibold text-cyan-700">Kondisi:</span> 
              <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">{{ product.condition }}</span>
          </p>
      </div>
      <div class="mt-3">
          <p class="text-base sm:text-lg text-gray-700 font-semibold text-cyan-700">Deskripsi:</p>
          <p class="text-base sm:text-lg text-gray-600 line-clamp-3 mt-1">{{ product.description }}</p>
      </div>
      <!-- Tombol edit dan hapus -->
      <div class="mt-auto">
        <div class="flex justify-center items-center space-x-4">
            <a href="{% url 'main:edit_product' product.id %}" class="text-base sm:text-xl bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-3 rounded transition duration-300">
                Edit
            </a>
            <a href="{% url 'main:hapus_product' product.id %}" class="text-base sm:text-xl bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-3 rounded transition duration-300">
                Hapus
            </a>
        </div>
      </div>
  </div>
</div>

main/templates/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Edit Deskripsi Produk</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mx-auto px-4 py-8">
    <!-- Product Edit Form Box -->
    <div class="bg-cyan-100 rounded-lg shadow-lg overflow-hidden mb-8">
        <div class="bg-gradient-to-r from-cyan-600 to-cyan-400 p-4">
            <h1 class="text-2xl sm:text-3xl font-bold text-center text-white">Edit Deskripsi Produk</h1>
        </div>
        <div class="p-6">
            <form method="POST" enctype="multipart/form-data" class="space-y-6">
                {% csrf_token %}
                {% for field in form %}
                    <div class="flex flex-col">
                        <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                            {{ field.label }}
                        </label>
                        <div class="w-full">
                            {% if field.name == 'image' %}
                                <div class="flex items-center space-x-4">
                                    <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-input w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" {% if field.field.required %}required{% endif %}>
                                    {% if product.image %}
                                        <img src="{{ product.image.url }}" alt="Current product image" class="w-16 h-16 object-cover rounded">
                                    {% endif %}
                                </div>
                            {% else %}
                                {{ field }}
                            {% endif %}
                        </div>
                        {% if field.help_text %}
                            <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                        {% endif %}
                        {% for error in field.errors %}
                            <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="flex justify-center mt-6">
                    <button type="submit" class="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-md transition duration-300 w-full">
                        Simpan Perubahan
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="flex items-center justify-center min-h-screen bg-gradient-to-b from-cyan-300 via-cyan-500 to-cyan-700">
    <div class="w-full max-w-md">
        <div class="bg-white shadow-lg rounded-lg px-8 pt-6 pb-8 mb-4">
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-cyan-800">Welcome to FindYourFits!</h1>
            </div>

            <form method="POST" action="">
                {% csrf_token %}
                <div class="mb-4">
                    <input type="text" name="username" id="username" placeholder="Username" class="w-full px-3 py-2 placeholder-gray-400 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent">
                </div>
                <div class="mb-6">
                    <input type="password" name="password" id="password" placeholder="Password" class="w-full px-3 py-2 placeholder-gray-400 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent">
                </div>
                <div class="mb-6">
                    <button type="submit" class="w-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-md transition duration-300">
                        Login
                    </button>
                </div>
            </form>

            <div class="text-center text-gray-600">
                <p>Belum punya akun? <a href="{% url 'main:register' %}" class="font-bold text-cyan-600 hover:text-cyan-800 transition duration-300">Daftar sekarang</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>FindYourFits</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="container mx-auto px-4 py-8 justify-center">
  <!-- Informasi akun -->
  <div class="bg-gradient-to-r from-cyan-950 to-cyan-700 rounded-lg shadow-lg p-6 mb-8 text-white">
      <h2 class="text-3xl sm:text-4xl font-bold mb-4 text-center">Welcome Back, {{ user.username }}</h2>
      <div class="text-center md:text-md sm:text-lg space-y-2">
        <p><span class="font-semibold">Nama:</span> {{ name }}</p>
        <p><span class="font-semibold">NPM:</span> {{ npm }}</p>
        <p><span class="font-semibold">Kelas:</span> {{ class }}</p>
        <p><span class="font-semibold">Last Login:</span> {{ last_login }}</p>
      </div>
  </div>

  <!-- List produk -->
  <div class="bg-white rounded-lg shadow-lg overflow-hidden mb-8">
    <div class="bg-gradient-to-r from-cyan-600 to-cyan-400 p-6">
        <h1 class="text-2xl sm:text-4xl font-bold text-white mb-4 text-center">List Produk</h1>
        <div class="flex space-x-4 justify-center">
            <a href="{% url 'main:sell_product_entry' %}" class="bg-white text-cyan-600 font-bold py-2 px-4 rounded-md hover:bg-cyan-100 transition duration-300">
                Tambah Produk
            </a>
            <button id="openModalButton" class="bg-white text-cyan-600 font-bold py-2 px-4 rounded-md hover:bg-cyan-100 transition duration-300">
              Tambah Produk (AJAX)
          </button>
        </div>
    </div>
    <div class="p-4 sm:p-6">
        <div id="product_entry_cards"></div>
    </div>
  </div>
</div>
<!-- Add Product Modal (AJAX) -->
<div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
  <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
    <!-- Modal header -->
    <div class="flex items-center justify-between p-4 border-b rounded-t bg-gradient-to-r from-cyan-600 to-cyan-400">
      <h3 class="text-xl font-semibold text-white">
        Tambah Produk Baru (AJAX)
      </h3>
    </div>
    <!-- Modal body -->
    <div class="px-6 py-4 space-y-6 form-style">
      <div id="errorMessage" class="hidden bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
        <strong class="font-bold">Error!</strong>
        <span class="block sm:inline" id="errorText"></span>
      </div>
      <form id="productEntryForm">
        {% csrf_token %}
        <div class="mb-4">
          <label for="name" class="block text-sm font-medium text-gray-700">Nama Produk</label>
          <input type="text" id="name" name="name" placeholder="Masukkan nama produk" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-cyan-600" required>
        </div>
        <div class="mb-4">
          <label for="price" class="block text-sm font-medium text-gray-700">Harga</label>
          <input type="number" id="price" name="price" placeholder="Masukkan harga produk" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-cyan-600" required>
        </div>
        <div class="mb-4">
          <label for="stock" class="block text-sm font-medium text-gray-700">Stok</label>
          <input type="number" id="stock" name="stock" placeholder="Masukkan jumlah stok" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-cyan-600" required>
        </div>
        <div class="mb-4">
          <label for="condition" class="block text-sm font-medium text-gray-700">Kondisi</label>
          <input type="text" id="condition" name="condition" placeholder="Contoh: Baru, Bekas" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-cyan-600" required>
        </div>
        <div class="mb-4">
          <label for="description" class="block text-sm font-medium text-gray-700">Deskripsi</label>
          <textarea id="description" name="description" rows="3" placeholder="Deskripsikan produk Anda" class="mt-1 block w-full resize-none border border-gray-300 rounded-md p-2 hover:border-cyan-600" required></textarea>
        </div>
      </form>
    </div>
    <!-- Modal footer -->
    <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
      <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Batal</button>
      <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-lg">Simpan</button>
    </div>
  </div>
</div>

<script>
  async function addProductEntry() {
    const form = document.getElementById('productEntryForm');
    const formData = new FormData(form);
    const errorMessage = document.getElementById('errorMessage');
    const errorText = document.getElementById('errorText');

    try {
        const response = await fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: formData,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
            },
        });

        const data = await response.json();

        if (response.ok) {
          form.reset();
          hideModal();
          try {
              await refreshProductEntries();
          } catch (refreshError) {
              console.error("Error saat refresh entries:", refreshError);
          }
          errorMessage.classList.add('hidden');
          return true;
      }
    } catch (error) {
        errorText.textContent = "Terjadi kesalahan saat menambahkan produk. Silahkan coba lagi.";
        errorMessage.classList.remove('hidden');
    } finally {
      refreshProductEntries();
      hideModal();
    }
}

  async function getProductEntries() {
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProductEntries() {
    document.getElementById("product_entry_cards").innerHTML = "";
    document.getElementById("product_entry_cards").className = "";
    const products = await getProductEntries();
    let htmlString = "";
    let classNameString = "";

    if (products.length === 0) {
      classNameString = `
        <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
          <img src="{% static 'image/sadface.png' %}" alt="Sad face" class="w-40 h-40 mb-6"/>
          <p class="text-center text-gray-600 text-xl mt-4">Belum ada produk yang ditemukan</p>
        </div>
      `;
    } else {
      classNameString = "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6";
      products.forEach((product) => {
        const name = DOMPurify.sanitize(product.fields.name);
        const description = DOMPurify.sanitize(product.fields.description);
        const condition = DOMPurify.sanitize(product.fields.condition);        
        htmlString += `
          <div class="bg-gradient-to-br from-white to-cyan-100 rounded-lg shadow-lg overflow-hidden flex flex-col h-full transform hover:scale-105 transition duration-300 border border-cyan-100">
            <div class="p-4 flex-grow flex flex-col">
              <h2 class="text-xl sm:text-2xl md:text-xl font-semibold mb-3 text-cyan-800 line-clamp-2">${name}</h2>
              <div class="space-y-2">
                <p class="text-base sm:text-lg text-gray-700">
                  <span class="font-semibold text-cyan-700">Harga:</span> 
                  <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">Rp. ${product.fields.price}</span>
                </p>
                <p class="text-base sm:text-lg text-gray-700">
                  <span class="font-semibold text-cyan-700">Stok:</span> 
                  <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">${product.fields.stock} pcs</span>
                </p>
                <p class="text-base sm:text-lg text-gray-700">
                  <span class="font-semibold text-cyan-700">Kondisi:</span> 
                  <span class="bg-cyan-100 text-cyan-800 px-2 py-1 rounded-full">${condition}</span>
                </p>
              </div>
              <div class="mt-3">
                <p class="text-base sm:text-lg text-gray-700 font-semibold text-cyan-700">Deskripsi:</p>
                <p class="text-base sm:text-lg text-gray-600 line-clamp-3 mt-1">${description}</p>
              </div>
              <div class="mt-auto">
                <div class="flex justify-center items-center space-x-4">
                  <a href="/edit-product/${product.pk}" class="text-base sm:text-xl bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-3 rounded transition duration-300">
                    Edit
                  </a>
                  <a href="/delete/${product.pk}" class="text-base sm:text-xl bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-3 rounded transition duration-300">
                    Hapus
                  </a>
                </div>
              </div>
            </div>
          </div>
        `;
      });
    }
    document.getElementById("product_entry_cards").className = classNameString;
    document.getElementById("product_entry_cards").innerHTML = htmlString;
  }
  refreshProductEntries();
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      console.log("hideModal function called");
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');
      const errorMessage = document.getElementById('errorMessage');
      
      if (!modal || !modalContent) {
          return;
      }
      
      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');
      if (errorMessage) {
          errorMessage.classList.add('hidden');
      }


      setTimeout(() => {
          modal.classList.add('hidden');
      }, 100); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("productEntryForm").addEventListener("submit", async (e) => {
    e.preventDefault();
    const success = await addProductEntry();
    if (!success) {
        // jika  gagal, modal tidak tertutup
        e.stopPropagation();
    }
  });
  document.getElementById("submitProductEntry").addEventListener("click", async (e) => {
    e.preventDefault();
    const form = document.getElementById('productEntryForm');
    if (form.checkValidity()) {
        const success = await addProductEntry();
    } else {
        form.reportValidity();
    }
});
  document.addEventListener('DOMContentLoaded', function() {
    const openModalButton = document.getElementById('openModalButton');
    if (openModalButton) {
        openModalButton.addEventListener('click', showModal);
    }
  });
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}

<div class="flex items-center justify-center min-h-screen bg-gradient-to-b from-cyan-300 via-cyan-500 to-cyan-700">
    <div class="w-full max-w-md">
        <div class="bg-white shadow-lg rounded-lg px-8 pt-6 pb-8 mb-4">
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-cyan-800">Buat Akun</h1>
            </div>

            <form method="POST" action="">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-4">
                        <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" placeholder="{{ field.label }}" class="w-full px-3 py-2 placeholder-gray-400 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-cyan-500 focus:border-transparent">
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class="mt-1 text-sm text-red-500">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="mb-6">
                    <button type="submit" class="w-full bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-md transition duration-300">
                        Daftar
                    </button>
                </div>
            </form>

            <div class="text-center text-gray-600">
                <p>Sudah punya akun? <a href="{% url 'main:login' %}" class="font-bold text-cyan-600 hover:text-cyan-800 transition duration-300">Login</a></p>
            </div>

            {% if messages %}
                <ul class="mt-3">
                    {% for message in messages %}
                        <li class="text-red-500 font-semibold">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

main/templates/sell_product_entry.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Produk ke Market</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container mx-auto px-4 py-8">
    <!-- Product Entry Box -->
    <div class="bg-cyan-100 rounded-lg shadow-lg overflow-hidden mb-8">
        <div class="bg-gradient-to-r from-cyan-600 to-cyan-400 p-4">
            <h1 class="text-2xl sm:text-3xl font-bold text-center text-white">Form Tambah Produk</h1>
        </div>
        <div class="p-6">
          <form method="POST" class="space-y-6">
              {% csrf_token %}
              {% for field in form %}
                  <div class="flex flex-col">
                      <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700">
                          {{ field.label }}
                      </label>
                      <div class="w-full">
                          {{ field }}
                      </div>
                      {% if field.help_text %}
                          <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                      {% endif %}
                      {% for error in field.errors %}
                          <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                      {% endfor %}
                  </div>
              {% endfor %}
              <div class="flex justify-center mt-6">
                  <button type="submit" class="bg-cyan-600 hover:bg-cyan-700 text-white font-bold py-2 px-4 rounded-md transition duration-300 w-full">
                      Tambahkan Produk
                  </button>
              </div>
          </form>
      </div>
  </div>
</div>
{% endblock %}